### ISSUE TITLE
Working with Venus OS 3.0x  ?

### ISSUE THREAD

**Issue by mettibuh** [davwil/venus_kostal_plenticore#10]
Hi,

does this script still work with the new version of Venus OS 3.0x?

I'm a little afraid of updating, because everything runs so nice and smooth - but the promised faster ESS control of the new version makes me also curious :-)

Thanks for your work!

**Comment by davwil** [comment]
Must admit that I did not have time to test that - let me know if you tested it :) It might make sense to install the new Venus version on a seperate SD card so that switching back to the old version is seemless if something does not work as intended.

**Comment by king-rulez** [comment]
I tested it on a Raspberry 3B with v3.10 and it didn't work.
Based on the error message I would say it is due to pycryptodomex.

**Comment by davwil** [comment]
Did you reinstall pycryptodomex?

**Comment by king-rulez** [comment]
no, do I absolutely have to?
If so, what is the command?

**Comment by davwil** [comment]
Looks like you're missing the dataclasses - i do not know your installation, but you could try to reinstall them, e.g. with `pip3 install dataclasses`
That's no issue within the code of this plugin :)
