### ISSUE TITLE
Download instructions in Install plugin section should include the -r option of scp

### ISSUE THREAD

**Issue by original-spaceman** [davwil/venus_kostal_plenticore#3]
Thank you very much for the plugin. Now Venus can see my Kostal Plenticore Plus :)

The example in the installation instructions for downloading via scp sould include the -r option, then it would be perfect, also for less experienced linux users - see below. Otherwise it will not download the folder service which contains run.

Install plugin:
.... (scp -r venus_kostal_plenticore/* root@venusip:/data/venus_kostal_plenticore/) ...

Thanks,
Bernd

**Comment by davwil** [comment]
Good point, thank's for pointing it out!  I've included the recursive flag in the Readme!
