### ISSUE TITLE
Getting wrong values from plenticore

### ISSUE THREAD

**Issue by pforrmi** [davwil/venus_kostal_plenticore#5]
Hi, sorry for open an issue again.

I was 100% sure that I installed the large os, but I won't have. So after I installed the correct one the plugin works directly.
But it's a little bit strange that I get some different values than from my Plenticore. Any idea why this happens?

E.g. my Plenticore shows actually 370W but in Venus OS it shows 312W. So not a small difference...

Appreciate your help!

**Comment by pforrmi** [comment]
Oh I think the different values are because of the difference between pv generator and pv inverter.... It's cause by the efficenty of the pv generatpr, right?

**Comment by davwil** [comment]
Yes - the kostal inverters report DC and AC power, naturally the DC power is higher due to inefficiencies and self consumption of the inverter.
The AC power is what's interesting, since that's the power available at the output of the inverter.
