### ISSUE TITLE
Error Python

### ISSUE THREAD

**Issue by bushvolcano** [davwil/venus_kostal_plenticore#7]
Hello I got the following Error Massage:

root@einstein:~# python data/venus_kostal_plenticore/kostal.py 
data/venus_kostal_plenticore/kostal.py:25: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  from gi.repository.GObject import idle_add
Parsing config: kostal.ini
config seems to be empty...

Config is definitely not empty.

**Comment by bushvolcano** [comment]
ok sorry, found my issue. I am not that familiar with Terminal. I just opened it up from wrong folder. 

But maybe the deprecated library can be changed

**Comment by davwil** [comment]
@bushvolcano I would appreciate a PR ;)
