### ISSUE TITLE
Consumption in VRM Portal to high

### ISSUE THREAD

**Issue by darvader** [davwil/venus_kostal_plenticore#8]
Maybe the energy of the script is missing?

![image](https://github.com/davwil/venus_kostal_plenticore/assets/15691420/358ff134-18d5-46fb-a1f2-c8bf34fdc494)

My real consumption is definitely lower. Do you have any tips and tricks for this issue?

Best regards
Andreas

**Comment by darvader** [comment]
I have found a solution for this. The energy should not be rounded. If you like, you can add me as a contributor, so I can create a pull request for it.

**Comment by davwil** [comment]
Thank's for you research, @darvader!
Unfurtunately I do not have a Kostal grid meter and thus cannot test whether the consumption is calculated correctly. I saw that you've already had opened a PR but that closed that one again. I'm happy to review and merge a your PR when you think that it's ready! 
I do not think that i need to add you as a contributor therefore.
